apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  labels:
    app: attendance-system
spec:
  type: LoadBalancer
  selector:
    app: attendance-system
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
